apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "basic-deployment.fullname" . }}
  labels:
    app: {{ include "basic-deployment.name" . }}
    chart: {{ include "basic-deployment.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
